---

- name: Basic secure Ubuntu
  hosts: minitask
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - resmo.ntp 

  tasks:
    - include: tasks/base.yml
    - include: tasks/ufw.yml

  handlers:
    - include: handlers/handlers.yml
