- name: Auto update in future
  apt:
    name: unattended-upgrades

- name: Update all
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Secure SSH config
  copy:
    src: files/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - restart sshd

- name: remote log if defined
  lineinfile:
    path: /etc/rsyslog.d/50-default.conf
    line: 'auth,authpriv.*     @@{{ syslog_server }}:514'
  when: syslog_server is defined and syslog_server != None

