- name: Auto update in future
  apt:
    name: unattended-upgrades

- name: Update all
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Secure SSH config
  copy:
    src: files/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - restart sshd
