---

# to verify ufw configuration run:
# sudo ufw status verbose

- name: Install ufw
  apt: package=ufw state=present

- name: Configure ufw defaults
  ufw: direction={{ item.direction }} policy={{ item.policy }}
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
  notify:
    - restart ufw

- name: Configure ufw rules
  ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }}
  with_items:
    - { rule: 'limit', port: '{{ ssh_port | default("22") }}', proto: 'tcp' }
  notify:
    - restart ufw

- name: Enable ufw logging
  ufw: logging=on
  notify:
    - restart ufw

- name: Enable ufw
  ufw: state=enabled

- name: remote log if defined
  lineinfile:
    path: /etc/rsyslog.d/20-ufw.conf
    line: ':msg,contains,"[UFW " @@{{syslog_server}}:514'
  when: syslog_server is defined and syslog_server != None
